import "../style/legal.scss"

function Terms() {
  return (
    <main className="legal-page">
      <div className="legal-container">
        <h1>Terms & Conditions</h1>
        <p className="legal-updated">Last updated: September 2026</p>

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using this application, you agree to these Terms &
            Conditions. If you do not agree with these terms, please do not use
            the application.
          </p>
        </section>

        <section>
          <h2>2. Description of the Service</h2>
          <p>
            This application provides AI-powered interview preparation
            features, including resume analysis, job-description matching,
            interview questions, skill-gap analysis, and personalized
            preparation plans.
          </p>
        </section>

        <section>
          <h2>3. User Accounts</h2>
          <p>
            You are responsible for providing accurate information when
            creating an account and for keeping your account credentials
            secure. You are responsible for activity carried out through your
            account.
          </p>
        </section>

        <section>
          <h2>4. User-Provided Content</h2>
          <p>
            You are responsible for the resume, job descriptions, self-
            descriptions, and other information that you upload or submit.
            You should only provide information that you have the right to
            submit and process.
          </p>
        </section>

        <section>
          <h2>5. AI-Generated Content</h2>
          <p>
            Interview questions, analysis, recommendations, preparation plans,
            and other results generated by the application are produced with
            the assistance of artificial intelligence.
          </p>
          <p>
            AI-generated results may contain errors, omissions, or inaccurate
            information. You should review generated content and use your own
            judgment when relying on it.
          </p>
        </section>

        <section>
          <h2>6. No Guarantee of Results</h2>
          <p>
            The application is intended as an interview preparation tool. It
            does not guarantee an interview invitation, job offer, employment,
            examination result, or any other particular outcome.
          </p>
        </section>

        <section>
          <h2>7. Acceptable Use</h2>
          <p>
            You agree not to misuse the application, attempt to gain
            unauthorized access, interfere with its operation, upload
            malicious content, or use the service for unlawful purposes.
          </p>
        </section>

        <section>
          <h2>8. Intellectual Property</h2>
          <p>
            The application's design, code, branding, and original content are
            protected by applicable intellectual property laws. You may use the
            service for its intended purpose but may not copy, redistribute,
            or commercially exploit the application without permission.
          </p>
        </section>

        <section>
          <h2>9. Third-Party Services</h2>
          <p>
            The application may use third-party services, including AI,
            database, hosting, and other infrastructure providers. Availability
            and operation of those services may be subject to their respective
            terms and policies.
          </p>
        </section>

        <section>
          <h2>10. Availability</h2>
          <p>
            We aim to keep the application available and functional, but we do
            not guarantee uninterrupted or error-free access. Features may be
            changed, suspended, or discontinued when necessary.
          </p>
        </section>

        <section>
          <h2>11. Limitation of Liability</h2>
          <p>
            To the extent permitted by applicable law, the developer is not
            responsible for losses resulting from reliance on AI-generated
            content, interruptions of service, third-party services, or
            user-provided information.
          </p>
        </section>

        <section>
          <h2>12. Changes to These Terms</h2>
          <p>
            These Terms & Conditions may be updated from time to time. Continued
            use of the application after changes are published constitutes
            acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2>13. Contact</h2>
          <p>
            If you have questions about these terms or need assistance, please
            use the Help link provided in the application.
          </p>
        </section>
      </div>
    </main>
  )
}

export default Terms